language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
script:
  - ./gradlew assembleDebug

before_deploy:
  - mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/noDrawable.apk

deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_AUTH}"
  file: app/build/outputs/apk/debug/noDrawable.apk
  skip_cleanup: true
  on:
    tags: true